export interface Template {
  id: string;
  title: string;
  description: string;
  tags: string[];
  duration: string;
  remotionId: string;
  fps: number;
  durationInFrames: number;
  width: number;
  height: number;
  videoUrl: string;
}

export const templates: Template[] = [
  {
    id: "product-launch",
    title: "Product Launch",
    description: "Cinematic reveal animation for product announcements with smooth entrance transitions and particle effects.",
    tags: ["Marketing", "Branding"],
    duration: "15s",
    remotionId: "ProductLaunch",
    fps: 30, durationInFrames: 450, width: 1920, height: 1080,
    videoUrl: "/videos/product-launch.mp4",
  },
  {
    id: "tutorial-intro",
    title: "Tutorial Intro",
    description: "Clean animated intro card for tutorials and online courses with title and chapter reveal.",
    tags: ["Tutorial", "Education"],
    duration: "8s",
    remotionId: "TutorialIntro",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/tutorial-intro.mp4",
  },
  {
    id: "saas-promo",
    title: "SaaS Promo",
    description: "Feature showcase animation for SaaS products with animated metric cards and smooth transitions.",
    tags: ["SaaS", "Marketing"],
    duration: "30s",
    remotionId: "SaaSPromo",
    fps: 30, durationInFrames: 900, width: 1920, height: 1080,
    videoUrl: "/videos/saas-promo.mp4",
  },
  {
    id: "social-story",
    title: "Social Story",
    description: "Vertical social media story template with animated text overlays and brand elements.",
    tags: ["Social", "Short-form"],
    duration: "10s",
    remotionId: "SocialStory",
    fps: 30, durationInFrames: 300, width: 1080, height: 1920,
    videoUrl: "/videos/social-story.mp4",
  },
  {
    id: "data-viz",
    title: "Data Viz",
    description: "Animated data visualization with smooth bar chart reveals and dynamic counter effects.",
    tags: ["Data", "Business"],
    duration: "20s",
    remotionId: "DataViz",
    fps: 30, durationInFrames: 600, width: 1920, height: 1080,
    videoUrl: "/videos/data-viz.mp4",
  },
  {
    id: "lower-third",
    title: "Lower Third",
    description: "Broadcast-style lower third with name and title slide-in animations for video productions.",
    tags: ["Broadcast", "Motion"],
    duration: "5s",
    remotionId: "LowerThird",
    fps: 30, durationInFrames: 150, width: 1920, height: 1080,
    videoUrl: "/videos/lower-third.mp4",
  },
  {
    id: "testimonial-card",
    title: "Testimonial Card",
    description: "Animated customer testimonial card with star rating reveal, quote, and author details.",
    tags: ["Marketing", "Social"],
    duration: "8s",
    remotionId: "TestimonialCard",
    fps: 30, durationInFrames: 240, width: 1080, height: 1080,
    videoUrl: "/videos/testimonial-card.mp4",
  },
  {
    id: "countdown-timer",
    title: "Countdown Timer",
    description: "Event countdown timer with Apple-style frosted glass cards and smooth number animations.",
    tags: ["Events", "Marketing"],
    duration: "7s",
    remotionId: "CountdownTimer",
    fps: 30, durationInFrames: 210, width: 1920, height: 1080,
    videoUrl: "/videos/countdown-timer.mp4",
  },
  {
    id: "brand-reveal",
    title: "Brand Reveal",
    description: "Elegant brand logo reveal with layered entrance animations and clean typography.",
    tags: ["Branding", "Marketing"],
    duration: "6s",
    remotionId: "BrandReveal",
    fps: 30, durationInFrames: 180, width: 1920, height: 1080,
    videoUrl: "/videos/brand-reveal.mp4",
  },
  {
    id: "vertical-story",
    title: "Vertical Story",
    description: "Full-screen vertical story format optimized for Instagram Reels, TikTok, and YouTube Shorts.",
    tags: ["Social", "Short-form"],
    duration: "10s",
    remotionId: "VerticalStory",
    fps: 30, durationInFrames: 300, width: 1080, height: 1920,
    videoUrl: "/videos/vertical-story.mp4",
  },
  {
    id: "end-screen",
    title: "End Screen",
    description: "Engaging YouTube-style end screen with subscribe CTA, video cards, and animated overlays.",
    tags: ["Marketing", "Tutorial"],
    duration: "7s",
    remotionId: "EndScreen",
    fps: 30, durationInFrames: 210, width: 1920, height: 1080,
    videoUrl: "/videos/end-screen.mp4",
  },
  {
    id: "metric-dashboard",
    title: "Metric Dashboard",
    description: "Animated KPI metrics and dashboard with real-time counter effects and progress indicators.",
    tags: ["Data", "SaaS"],
    duration: "8s",
    remotionId: "MetricDashboard",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/metric-dashboard.mp4",
  },
  {
    id: "typewriter-quote",
    title: "Typewriter Quote",
    description: "Typewriter-style animated quote reveal with clean Apple Light Mode typography.",
    tags: ["Social", "Motion"],
    duration: "8s",
    remotionId: "TypewriterQuote",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/typewriter-quote.mp4",
  },
  {
    id: "dynamic-island",
    title: "Dynamic Island",
    description: "Apple Dynamic Island notification animation with spring physics and incoming call UI.",
    tags: ["Tech", "Motion"],
    duration: "5s",
    remotionId: "DynamicIsland",
    fps: 30, durationInFrames: 150, width: 1920, height: 1080,
    videoUrl: "/videos/dynamic-island.mp4",
  },
  {
    id: "pricing-card",
    title: "Pricing Card",
    description: "Pricing plan card with animated feature list reveal, highlight badge, and CTA entrance.",
    tags: ["SaaS", "Marketing"],
    duration: "8s",
    remotionId: "PricingCard",
    fps: 30, durationInFrames: 240, width: 1080, height: 1080,
    videoUrl: "/videos/pricing-card.mp4",
  },
  {
    id: "bar-chart",
    title: "Bar Chart",
    description: "Animated bar chart with smooth grow-in effects and data labels for presentations.",
    tags: ["Data", "Business"],
    duration: "8s",
    remotionId: "BarChart",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/bar-chart.mp4",
  },
  {
    id: "split-reveal",
    title: "Split Reveal",
    description: "Split-screen panel reveal with contrasting sides and animated text entrance.",
    tags: ["Branding", "Motion"],
    duration: "6s",
    remotionId: "SplitReveal",
    fps: 30, durationInFrames: 180, width: 1920, height: 1080,
    videoUrl: "/videos/split-reveal.mp4",
  },
  {
    id: "event-promo",
    title: "Event Promo",
    description: "Stylish event promotion with animated date, venue, and speaker card reveals.",
    tags: ["Events", "Marketing"],
    duration: "8s",
    remotionId: "EventPromo",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/event-promo.mp4",
  },
  {
    id: "subscribe-cta",
    title: "Subscribe CTA",
    description: "Animated subscribe call-to-action for YouTube creators with bell icon and channel branding.",
    tags: ["Marketing", "Social"],
    duration: "6s",
    remotionId: "SubscribeCTA",
    fps: 30, durationInFrames: 180, width: 1920, height: 1080,
    videoUrl: "/videos/subscribe-cta.mp4",
  },
  {
    id: "news-breaking",
    title: "News Breaking",
    description: "Apple Light Mode news broadcast with floating frosted-glass cards, animated ticker, and LIVE badge.",
    tags: ["Broadcast", "Motion"],
    duration: "10s",
    remotionId: "NewsBreaking",
    fps: 30, durationInFrames: 300, width: 1920, height: 1080,
    videoUrl: "/videos/news-breaking.mp4",
  },
  {
    id: "minimal-title",
    title: "Minimal Title",
    description: "Ultra-minimal title card with precise typography animation and subtle fade transitions.",
    tags: ["Motion", "Branding"],
    duration: "5s",
    remotionId: "MinimalTitle",
    fps: 30, durationInFrames: 150, width: 1920, height: 1080,
    videoUrl: "/videos/minimal-title.mp4",
  },
  {
    id: "gradient-reveal",
    title: "Gradient Reveal",
    description: "Smooth gradient mesh reveal with layered color transitions and animated composition.",
    tags: ["Branding", "Motion"],
    duration: "6s",
    remotionId: "GradientReveal",
    fps: 30, durationInFrames: 180, width: 1920, height: 1080,
    videoUrl: "/videos/gradient-reveal.mp4",
  },
  {
    id: "team-grid",
    title: "Team Grid",
    description: "Animated team member grid with staggered card entrances for company introductions.",
    tags: ["Business", "Marketing"],
    duration: "8s",
    remotionId: "TeamGrid",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/team-grid.mp4",
  },
  {
    id: "quote-story",
    title: "Quote Story",
    description: "Vertical quote card with elegant author reveal for social media stories.",
    tags: ["Social", "Short-form"],
    duration: "8s",
    remotionId: "QuoteStory",
    fps: 30, durationInFrames: 240, width: 1080, height: 1920,
    videoUrl: "/videos/quote-story.mp4",
  },
  {
    id: "timeline",
    title: "Timeline",
    description: "Alternating card timeline with staggered reveal animations for company history or roadmaps.",
    tags: ["Business", "Tutorial"],
    duration: "9s",
    remotionId: "Timeline",
    fps: 30, durationInFrames: 270, width: 1920, height: 1080,
    videoUrl: "/videos/timeline.mp4",
  },
  {
    id: "web-promo",
    title: "Web Promo",
    description: "Browser mockup promo with animated UI elements and feature highlights for web apps.",
    tags: ["Marketing", "SaaS"],
    duration: "10s",
    remotionId: "WebPromo",
    fps: 30, durationInFrames: 300, width: 1920, height: 1080,
    videoUrl: "/videos/web-promo.mp4",
  },
  {
    id: "celebration-burst",
    title: "Celebration Burst",
    description: "Confetti burst celebration animation with particle physics for announcements and milestones.",
    tags: ["Events", "Social"],
    duration: "6s",
    remotionId: "CelebrationBurst",
    fps: 30, durationInFrames: 180, width: 1080, height: 1080,
    videoUrl: "/videos/celebration-burst.mp4",
  },
  {
    id: "code-reveal",
    title: "Code Reveal",
    description: "Code editor-style character-by-character typewriter reveal for developer tutorials and demos.",
    tags: ["Developer", "Tutorial"],
    duration: "10s",
    remotionId: "CodeReveal",
    fps: 30, durationInFrames: 300, width: 1920, height: 1080,
    videoUrl: "/videos/code-reveal.mp4",
  },
  {
    id: "product-card",
    title: "Product Card",
    description: "E-commerce product card animation with shimmer reveal, pricing, star rating, and CTA button.",
    tags: ["eCommerce", "Marketing"],
    duration: "6s",
    remotionId: "ProductCard",
    fps: 30, durationInFrames: 180, width: 1080, height: 1080,
    videoUrl: "/videos/product-card.mp4",
  },
  {
    id: "ai-animation",
    title: "AI Generation",
    description: "Apple-style animation simulating an AI prompt being typed and generating a UI component in real time.",
    tags: ["AI", "Tech", "SaaS"],
    duration: "8s",
    remotionId: "AiAnimation",
    fps: 30, durationInFrames: 240, width: 1920, height: 1080,
    videoUrl: "/videos/ai-animation.mp4",
  },
];

export const TAG_COLORS: Record<string, string> = {
  Marketing:    "bg-blue-50 text-blue-600 border-blue-200",
  Branding:     "bg-violet-50 text-violet-600 border-violet-200",
  SaaS:         "bg-purple-50 text-purple-600 border-purple-200",
  Tutorial:     "bg-green-50 text-green-600 border-green-200",
  Education:    "bg-teal-50 text-teal-600 border-teal-200",
  Social:       "bg-pink-50 text-pink-600 border-pink-200",
  "Short-form": "bg-rose-50 text-rose-600 border-rose-200",
  Data:         "bg-amber-50 text-amber-600 border-amber-200",
  Business:     "bg-orange-50 text-orange-600 border-orange-200",
  Broadcast:    "bg-cyan-50 text-cyan-600 border-cyan-200",
  Motion:       "bg-sky-50 text-sky-600 border-sky-200",
  Events:       "bg-indigo-50 text-indigo-600 border-indigo-200",
  Tech:         "bg-slate-50 text-slate-600 border-slate-200",
  Developer:    "bg-zinc-50 text-zinc-600 border-zinc-200",
  eCommerce:    "bg-lime-50 text-lime-600 border-lime-200",
  AI:           "bg-fuchsia-50 text-fuchsia-600 border-fuchsia-200",
};
